"use client";

import React, { useState, useContext, useEffect } from "react";
import { useRouter } from "next/navigation";
import { jwtDecode } from "jwt-decode";
import { UserContext } from "./providers/UserProvider";
import Header from "./components/Header";
import Stories from "./components/Stories";
import CreatePost from "./components/CreatePost";
import PostCard from "./components/PostCard";
import Sidebar from "./components/SideBar";

const API_URL = process.env.NEXT_PUBLIC_API_URL;

type User = {
  _id: string;
  username: string;
  fullname: string;
};

type PostType = {
  _id: string;
  user: {
    _id: string;
    username: string;
    fullname: string;
  };
  imageUrl: string;
  description: string;
  liked: boolean;
  likes: number;
  likedUsers?: string[];
  createdAt: string;
  updatedAt?: string;
};

type JWTPayload = {
  id: string;
  username: string;
  fullname?: string;
};

export default function Home() {
  const { user, setUser } = useContext(UserContext);
  const [users, setUsers] = useState<User[]>([]);
  const [posts, setPosts] = useState<PostType[]>([]);
  const [loading, setLoading] = useState(true);
  const [newPostDescription, setNewPostDescription] = useState("");
  const [newPostImage, setNewPostImage] = useState("");
  const [posting, setPosting] = useState(false);

  const router = useRouter();

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/signin");
      return;
    }

    try {
      const payload: JWTPayload = jwtDecode(token);
      if (!payload.id || !payload.username) throw new Error("Invalid token");

      setUser({
        _id: payload.id,
        username: payload.username,
        fullname: payload.fullname || "No Name",
        avatar: undefined,
        password: "",
        email: null,
        phone: null,
      });

      setLoading(false);
    } catch (err) {
      console.error("JWT invalid:", err);
      localStorage.removeItem("token");
      router.push("/signin");
    }
  }, [router, setUser]);

  useEffect(() => {
    async function fetchUsers() {
      const token = localStorage.getItem("token");
      if (!token) return;

      try {
        const res = await fetch(`${API_URL}/users`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data = await res.json();
        setUsers(data.body || []);
      } catch (err) {
        console.error("Failed to fetch users:", err);
      }
    }

    fetchUsers();
  }, []);

  useEffect(() => {
    async function fetchPosts() {
      const token = localStorage.getItem("token");
      if (!token || !user) return;

      try {
        const res = await fetch(`${API_URL}/posts`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const data: PostType[] = await res.json();

        setPosts(
          data.map((p) => ({
            ...p,
            liked: p.likedUsers?.includes(user._id) ?? false,
          }))
        );
      } catch (err) {
        console.error("Failed to fetch posts:", err);
      }
    }

    fetchPosts();
  }, [user]);

  if (loading || !user) return <div>Loading...</div>;

  const toggleLike = async (postId: string) => {
    const post = posts.find((p) => p._id === postId);
    if (!post || !user) return;

    try {
      const res = await fetch(`${API_URL}/posts/${postId}/like`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ userId: user._id }),
      });

      const data = await res.json();
      if (!res.ok) return console.error("Like failed:", data.message);

      setPosts((prev) =>
        prev.map((p) =>
          p._id === postId ? { ...p, liked: !p.liked, likes: data.likes } : p
        )
      );
    } catch (err) {
      console.error("Error liking post:", err);
    }
  };

  const createPost = async () => {
    if (!newPostDescription || !newPostImage || !user) return;
    setPosting(true);

    const token = localStorage.getItem("token");

    try {
      const res = await fetch(`${API_URL}/posts`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          description: newPostDescription,
          imageUrl: newPostImage, // generated by Google AI
          userId: user._id,
        }),
      });

      const data = await res.json();
      if (!res.ok) return console.error("Failed to create post:", data.message);

      setPosts((prev) => [
        {
          _id: data.body._id,
          user: {
            _id: user._id,
            username: user.username,
            fullname: user.fullname,
          },
          imageUrl: newPostImage,
          description: newPostDescription,
          liked: false,
          likes: 0,
          createdAt: data.body.createdAt,
          updatedAt: data.body.updatedAt,
        },
        ...prev,
      ]);

      setNewPostDescription("");
      setNewPostImage("");
    } catch (err) {
      console.error("Error creating post:", err);
    } finally {
      setPosting(false);
    }
  };

  const deletePost = async (postId: string) => {
    if (!user) return;
    const token = localStorage.getItem("token");
    if (!token) return;

    try {
      const res = await fetch(`${API_URL}/posts/${postId}`, {
        method: "DELETE",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ userId: user._id }),
      });

      const data = await res.json();
      if (!res.ok) return console.error("Failed to delete post:", data.message);

      setPosts((prev) => prev.filter((p) => p._id !== postId));
    } catch (err) {
      console.error("Error deleting post:", err);
    }
  };

  const editPost = async (postId: string, newDescription: string) => {
    if (!user) return;
    const token = localStorage.getItem("token");
    if (!token) return;

    try {
      const res = await fetch(`${API_URL}/posts/${postId}`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ userId: user._id, description: newDescription }),
      });

      const data = await res.json();
      if (!res.ok) return console.error("Failed to edit post:", data.message);

      setPosts((prev) =>
        prev.map((p) =>
          p._id === postId ? { ...p, description: newDescription } : p
        )
      );
    } catch (err) {
      console.error("Error editing post:", err);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900">
      <Header />
      <Stories users={users} />

      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 lg:grid-cols-3 gap-6 py-6">
        <section className="lg:col-span-2 flex flex-col">
          <CreatePost
            description={newPostDescription}
            setDescription={setNewPostDescription}
            imageUrl={newPostImage}
            setImageUrl={setNewPostImage}
            createPost={createPost}
            posting={posting}
          />

          {posts.map((post) => (
            <PostCard
              key={post._id}
              post={post}
              toggleLike={toggleLike}
              currentUserId={user._id}
              deletePost={deletePost}
              editPost={editPost}
            />
          ))}
        </section>

        <Sidebar username={user.username} fullname={user.fullname} />
      </main>
    </div>
  );
}
